name: Ghost Repository to Public

on:
  push:
    branches:
      - main

jobs:
  ghost-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create backup branch
        run: |
          git branch backup-before-ghost-$(date +%Y%m%d-%H%M%S) HEAD
          git push origin backup-before-ghost-$(date +%Y%m%d-%H%M%S)

      - name: Set remote URL and rewrite history
        env:
          ROBOT_GITHUB_TOKEN: ${{ secrets.ROBOT_GITHUB_TOKEN }}
          TARGET_REPO: "whitebit-exchange/api-documentation"
          ROBOT_NAME: "whitebit-robot"
          ROBOT_EMAIL: "robot@whitebit.com"
        run: |
          git remote set-url origin https://${{ env.ROBOT_NAME }}:${{ env.ROBOT_GITHUB_TOKEN }}@github.com/${{ env.TARGET_REPO }}.git
          git filter-branch -f --env-filter "
            GIT_AUTHOR_NAME='${{ env.ROBOT_NAME }}'
            GIT_AUTHOR_EMAIL='${{ env.ROBOT_EMAIL }}'
            GIT_COMMITTER_NAME='${{ env.ROBOT_NAME }}'
            GIT_COMMITTER_EMAIL='${{ env.ROBOT_EMAIL }}'
          " HEAD

      - name: Push to target repository
        run: |
          git push --force -u origin
