name: Rename All Committers

on:
  workflow_dispatch:
    inputs:
      new_email:
        description: 'New email address for all committers'
        required: true
        default: 'joh@whitebit.com'
        type: string
      new_name:
        description: 'New name for all committers'
        required: true
        default: 'joh'
        type: string
      confirm_rewrite:
        description: 'Type "CONFIRM_REWRITE" to proceed with history rewrite'
        required: true
        type: string

jobs:
  rename-committers:
    runs-on: ubuntu-latest
    steps:
      - name: Validate confirmation
        if: ${{ github.event.inputs.confirm_rewrite != 'CONFIRM_REWRITE' }}
        run: |
          echo "❌ ERROR: You must type 'CONFIRM_REWRITE' to proceed with this dangerous operation"
          echo "This operation will:"
          echo "  - Rewrite the entire git history"
          echo "  - Change all commit SHAs"
          echo "  - Break existing references, PRs, and deployments"
          echo "  - Cannot be easily reversed once pushed"
          exit 1

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install git-filter-repo
        run: |
          python3 -m pip install --user git-filter-repo

      - name: Configure git
        run: |
          git config --global user.name "${{ github.event.inputs.new_name }}"
          git config --global user.email "${{ github.event.inputs.new_email }}"

      - name: Show current committer statistics
        run: |
          echo "=== Current Committer Statistics ==="
          git log --format='%aN <%aE>' | sort | uniq -c | sort -rn
          echo ""
          echo "=== Total commits ==="
          git rev-list --count HEAD

      - name: Create backup branch
        run: |
          git branch backup-before-rewrite HEAD
          git push origin backup-before-rewrite

      - name: Rewrite git history to change all committers
        run: |
          # Use git filter-repo to rewrite all author and committer information
          git filter-repo --force \
            --name-callback 'return b"${{ github.event.inputs.new_name }}"' \
            --email-callback 'return b"${{ github.event.inputs.new_email }}"'

      - name: Show new committer statistics
        run: |
          echo "=== New Committer Statistics ==="
          git log --format='%aN <%aE>' | sort | uniq -c | sort -rn
          echo ""
          echo "=== Total commits ==="
          git rev-list --count HEAD

      - name: Force push the rewritten history
        run: |
          git push --force-with-lease origin HEAD:${{ github.ref_name }}

      - name: Create summary
        run: |
          echo "✅ Git history rewrite completed successfully!"
          echo ""
          echo "📊 Summary:"
          echo "  - All committers renamed to: ${{ github.event.inputs.new_name }} <${{ github.event.inputs.new_email }}>"
          echo "  - Backup branch created: backup-before-rewrite"
          echo "  - Branch updated: ${{ github.ref_name }}"
          echo ""
          echo "⚠️  Important notes:"
          echo "  - All commit SHAs have changed"
          echo "  - Existing PRs and references may be broken"
          echo "  - Team members will need to reset their local repositories"
          echo "  - To restore original history: git reset --hard origin/backup-before-rewrite"