name: Rename All Committers

on:
  workflow_dispatch:
    inputs:
      new_email:
        description: 'New email address for all committers'
        required: true
        default: 'robot@whitebit.com'
        type: string
      new_name:
        description: 'New name for all committers'
        required: true
        default: 'whitebit-robot'
        type: string
      github_token:
        description: 'GitHub token for authentication'
        required: true
        type: string
      target_repo:
        description: 'Target repository URL'
        required: true
        default: 'whitebit-exchange/api-documentation'
        type: string
      confirm_rewrite:
        description: 'Type "CONFIRM_REWRITE" to proceed with history rewrite'
        required: true
        type: string

jobs:
  rename-committers:
    runs-on: ubuntu-latest
    steps:
      - name: Validate confirmation
        if: ${{ github.event.inputs.confirm_rewrite != 'CONFIRM_REWRITE' }}
        run: |
          echo "❌ ERROR: You must type 'CONFIRM_REWRITE' to proceed with this dangerous operation"
          echo "This operation will:"
          echo "  - Rewrite the entire git history"
          echo "  - Change all commit SHAs"
          echo "  - Break existing references, PRs, and deployments"
          echo "  - Cannot be easily reversed once pushed"
          exit 1

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git
        run: |
          git config --global user.name "${{ github.event.inputs.new_name }}"
          git config --global user.email "${{ github.event.inputs.new_email }}"

      - name: Show current committer statistics
        run: |
          echo "=== Current Committer Statistics ==="
          git log --format='%aN <%aE>' | sort | uniq -c | sort -rn
          echo ""
          echo "=== Total commits ==="
          git rev-list --count HEAD

      - name: Set remote URL with token
        run: |
          git remote set-url origin https://whitebit-robot:${{ github.event.inputs.github_token }}@github.com/${{ github.event.inputs.target_repo }}.git

      - name: Create backup branch
        run: |
          git branch backup-before-rewrite HEAD
          git push origin backup-before-rewrite

      - name: Rewrite git history to change all committers
        run: |
          # Use git filter-branch to rewrite all author and committer information
          git filter-branch -f --env-filter "
            GIT_AUTHOR_NAME='${{ github.event.inputs.new_name }}'
            GIT_AUTHOR_EMAIL='${{ github.event.inputs.new_email }}'
            GIT_COMMITTER_NAME='${{ github.event.inputs.new_name }}'
            GIT_COMMITTER_EMAIL='${{ github.event.inputs.new_email }}'
          " HEAD

      - name: Show new committer statistics
        run: |
          echo "=== New Committer Statistics ==="
          git log --format='%aN <%aE>' | sort | uniq -c | sort -rn
          echo ""
          echo "=== Total commits ==="
          git rev-list --count HEAD

      - name: Force push the rewritten history
        run: |
          git push --force -u origin

      - name: Create summary
        run: |
          echo "✅ Git history rewrite completed successfully!"
          echo ""
          echo "📊 Summary:"
          echo "  - All committers renamed to: ${{ github.event.inputs.new_name }} <${{ github.event.inputs.new_email }}>"
          echo "  - Backup branch created: backup-before-rewrite"
          echo "  - Branch updated: ${{ github.ref_name }}"
          echo ""
          echo "⚠️  Important notes:"
          echo "  - All commit SHAs have changed"
          echo "  - Existing PRs and references may be broken"
          echo "  - Team members will need to reset their local repositories"
          echo "  - To restore original history: git reset --hard origin/backup-before-rewrite"